name: Bump version
description: Bumps the version or sets it to the provided version

inputs:
  version:
    description: Image version tag
    required: false
  github_token:
    description: GITHUB_TOKEN
    required: true
outputs:
  version:
    description: The calculated version
    value: ${{ steps.autoVersion.outputs.new_tag || steps.manualVersion.outputs.new_tag }}

runs:
  using: composite
  steps:
  - if: ${{ inputs.version != '' }}
    id: manualVersion
    name: Manual version
    uses: mathieudutour/github-tag-action@v6.0
    with:
      github_token: ${{ inputs.github_token }}
      custom_tag: ${{ inputs.version }}
      tag_prefix: ''
      dry_run: ${{ inputs.version == 'test' }}
  - if: ${{ inputs.version == '' }}
    id: autoVersion
    name: Automatic version
    uses: mathieudutour/github-tag-action@v6.0
    with:
      github_token: ${{ inputs.github_token }}
      tag_prefix: ''