# flow:
# - update kubernetes deployment

name: Deploy Image

on:
  workflow_call:
    inputs:
      version_number:
        type: string
        description: Image version tag
        required: true
  workflow_dispatch:
    inputs:
      version_number:
        description: Image version tag
        required: true

jobs:
  deploy:
    needs: build
    name: Deploy
    runs-on: self-hosted
    steps:
    - run: echo ${{ version_number }}
    # add image to kube!