name: Deploy Image

on:
  workflow_call:
    inputs:
      version:
        type: string
        required: true
  workflow_dispatch:
    inputs:
      version:
        description: Image version to deploy
        required: true

jobs:
  pull:
    name: Pull repository
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v2.4.2
  
  deploy:
    name: Deploy image
    runs-on: self-hosted
    steps:
    - name: Deploy
      uses: ./.github/actions/deploy-image
      with:
        version: ${{ inputs.version }}

  cleanup:
    needs: deploy
    name: Cleanup
    runs-on: self-hosted
    steps:
    - name: Cleanup
      uses: rtCamp/action-cleanup@master