# This is a basic workflow to help you get started with Actions

name: Deploy

on:
  pull_request_target:
    types:
      - closed
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2.4.2
