name: Deploy

on:
  pull_request_target:
    types:
      - closed
    branches:
      - master
  workflow_dispatch:
    inputs:
      version_number:
        description: 'Version number for the release'
        required: false
        default: ''

jobs:
  pull:
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2.4.2
      with:
        fetch-depth: '0'

  bumpVersion:
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch' 
    runs-on: self-hosted
    steps:
    - if: github.event.inputs.version_number != ''
      name: 'manual version'
      uses: anothrNick/github-tag-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - if: github.event.inputs.version_number == ''
      name: 'auto bump'
      uses: anothrNick/github-tag-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CUSTOM_TAG: ${{ github.event.inputs.version_number }}
